### ISSUE TITLE
podspec with dylib

### ISSUE THREAD

**Issue by hons82** [andreacremaschi/geos-fat-dynamic-bitcode#1]
Hi,

Ive seen [your post](https://github.com/CocoaPods/CocoaPods/issues/4474) and currently I'm running into the same issue. 
I've a created a dylib and made a podspec with it. This dylib I'd like to use in another pod.
I'm at the point that I can compile everything, but then at runtime it is not able to find the library.

Did you manage to get this working?

**Comment by andreacremaschi** [comment]
No :)
I ended just dropping the experiment because of other issues I couldn't resolve, sorry
